import { ArrowDownRight, ArrowUpRight, Code2, Contact, Mail, MapPin, Sparkles } from 'lucide-react';

const skills = [
  { title: 'Languages', items: ['Python', 'C++', 'Java', 'Dart', 'SQL', 'Bash'] },
  { title: 'Frameworks & tools', items: ['Flutter', 'Git', 'GitHub', 'VS Code', 'CMake', 'Docker', 'Firebase'] },
  { title: 'Data & systems', items: ['Firestore', 'SQLite', 'MySQL', 'Kali Linux', 'Fedora', 'Windows'] },
  { title: 'Specialties', items: ['Manual Testing', 'Test Planning', 'Bug Reporting', 'Nmap', 'Wireshark', 'Burp Suite', 'YOLO', 'OpenCV'] },
];
const projects = [
  { number: '01', title: 'Pharmacy Management System', description: 'An integrated system for medicine management, point of sale, and expiration date tracking.', tags: ['Java', 'C++', 'Python', 'Flutter', 'Firebase'] },
  { number: '02', title: 'Store & Inventory Management', description: 'A sales and warehouse system with inventory reports and intelligent low-stock alerts.', tags: ['Java', 'C++', 'Python', 'Flutter', 'Firebase'] },
  { number: '03', title: 'Full-Stack AI Web Chatbot', description: 'A dynamic conversational application powered by Gemini API with secure cloud storage.', tags: ['Gemini API', 'Firebase', 'Full-Stack'] },
  { number: '04', title: 'Subsurface Object Detection', description: 'A computer vision model that detects underground objects from GPR imagery.', tags: ['YOLO', 'Python', 'OpenCV', 'GPR'] },
];
function SectionTitle({ eyebrow, title, id }: { eyebrow: string; title: string; id: string }) { return <div className="section-heading" id={id}><span>{eyebrow}</span><h2>{title}</h2></div>; }

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="monogram" href="#top" aria-label="Home">N<span>•</span></a><div className="nav-links"><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a></div><a className="nav-cta" href="mailto:nabosallem@gmail.com">Let’s talk <ArrowUpRight size={16}/></a></nav>
    <section className="hero shell" id="top"><div className="hero-orb" aria-hidden="true"><div className="orb-core">NM</div><span className="orbit orbit-one"/><span className="orbit orbit-two"/></div><div className="hero-copy"><p className="availability"><span/> Available for opportunities</p><p className="intro">Hello, I’m</p><h1>NABEEH<br/><em>MOHAMED</em></h1><p className="role">AI Student <b>•</b> Software Developer <b>•</b><br/> QA & Cybersecurity</p><div className="hero-actions"><a className="primary-button" href="https://github.com/nabosallem-svg" target="_blank" rel="noreferrer"><Code2 size={19}/> View GitHub <ArrowUpRight size={17}/></a><a className="text-link" href="#projects">Explore my work <ArrowDownRight size={17}/></a></div></div><div className="hero-index" aria-hidden="true">01 <span>/ 04</span></div></section>
    <section className="about shell section-pad" id="about"><SectionTitle eyebrow="01 / About" title="Building reliable ideas into real products." id="about-title"/><div className="about-grid"><p className="about-lead">I’m an AI & Science student at <span>Horus University</span>, graduating in 2029 — driven by the space where intelligent systems, thoughtful software, and security meet.</p><div className="about-detail"><p>I build software systems from the ground up: shaping user interfaces, engineering applications, and designing the databases beneath them.</p><p>My QA background brings a critical eye to every project through manual testing, test planning, and precise bug reporting. I’m also exploring cybersecurity to build things that don’t just work — but hold up.</p></div></div><div className="about-meta"><span><MapPin size={16}/> Egypt</span><span><Sparkles size={16}/> AI & Science · Class of 2029</span></div></section>
    <section className="skills-section section-pad" id="skills"><div className="shell"><SectionTitle eyebrow="02 / Toolkit" title="Skills & technologies" id="skills-title"/><div className="skill-grid">{skills.map(group=><article className="skill-card" key={group.title}><h3>{group.title}</h3><div>{group.items.map(item=><span key={item}>{item}</span>)}</div></article>)}</div></div></section>
    <section className="projects shell section-pad" id="projects"><SectionTitle eyebrow="03 / Selected work" title="Projects made to solve." id="projects-title"/><div className="project-list">{projects.map(project=><article className="project-card" key={project.number}><div className="project-image"><span>{project.number}</span><div className="image-mark">PROJECT<br/>PREVIEW</div></div><div className="project-content"><p className="project-number">PROJECT / {project.number}</p><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div><span className="project-arrow"><ArrowUpRight/></span></article>)}</div></section>
    <footer className="footer" id="contact"><div className="shell"><p className="footer-kicker">04 / Contact</p><h2>Have a project in mind?<br/><em>Let’s build it.</em></h2><a className="email" href="mailto:nabosallem@gmail.com">nabosallem@gmail.com <ArrowUpRight/></a><div className="footer-bottom"><p>© 2026 Nabeeh Mohamed</p><div><a href="https://github.com/nabosallem-svg" target="_blank" rel="noreferrer"><Code2 size={18}/> GitHub</a><a href="https://linkedin.com/in/nabeeh-mohamed-91b2aa386" target="_blank" rel="noreferrer"><Contact size={18}/> LinkedIn</a><a href="mailto:nabosallem@gmail.com"><Mail size={18}/> Email</a></div></div></div></footer>
  </main>;
}
