// ==========================================
// /* ★★★ ALL PROJECTS — EDIT LINKS / TEXT HERE ★★★ */
// Each project can have a GitHub link and an Open/Live link. Leave either as '' to hide that button.
// For APK/JAR (paths starting with "/"), the modal adds the `download` attribute automatically.
// `group` drives the filter chips above the grid.
// ==========================================

import { outputs } from './outputs';

export type ProjectGroup = 'security' | 'software' | 'ai' | 'web' | 'depi';

export type Project = {
  id: string;
  type: string;
  title: string;
  desc: string;
  tech: string[];
  year: string;
  image?: string;
  github: string;
  demo: string;
  demoLabel: string;
  howTitle: string;
  how: string;
  run: string;
  featured: boolean;
  group: ProjectGroup;
  /** Recorded walkthrough shown at the top of the modal instead of the image. */
  video?: string;
  /** Extra in-browser demo shown as its own button (e.g. a web build next to an APK). */
  live?: string;
  liveLabel?: string;
  /** Real console output shown in the modal (see outputs.ts). */
  output?: string;
};

export const groups: { key: 'all' | ProjectGroup; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'security', label: 'Security' },
  { key: 'software', label: 'Software' },
  { key: 'web', label: 'Web' },
  { key: 'ai', label: 'AI' },
  { key: 'depi', label: 'DEPI Training' },
];

const list: Project[] = [
  {
    id: '01',
    type: 'SaaS · Security — Featured',
    title: 'RedPulse / ReconPilot',
    desc: 'Automated penetration testing platform — subdomain discovery, live probing and vulnerability scanning with reporting.',
    tech: ['FastAPI', 'Next.js', 'Supabase', 'Vercel'],
    year: '2026',
    image: '/assets/project-reconpilot.png',
    github: 'https://github.com/nabosallem-svg/RedPulse',
    demo: 'https://redpulse-frontend.vercel.app',
    demoLabel: 'Launch RedPulse',
    howTitle: 'How it works',
    how: 'FastAPI runs Subfinder → httpx → Nuclei/Nmap → stores assets & findings in PostgreSQL → Next.js dashboard shows results with real-time status. Auth via Supabase, payments via Stripe.',
    run: '1) Clone: git clone https://github.com/nabosallem-svg/RedPulse\n2) cd reconpilot && cp .env.example .env\n3) docker-compose up  →  frontend http://localhost:3000  |  api http://localhost:8000',
    featured: true,
    group: 'security',
  },
  {
    id: '02',
    type: 'Business Software',
    title: 'Data Gris Store',
    desc: 'Comprehensive store & inventory system — POS, suppliers, purchases, sales, barcode, treasury and commissions. Built with my friend.',
    tech: ['Dart', 'Hive', 'Firebase'],
    year: '2025',
    image: '/assets/project-store.png',
    github: 'https://github.com/nabosallem-svg/DataGris-Store',
    demo: '/DataGris-App.apk',
    demoLabel: 'Download APK',
    live: '/demos/datagris-store/',
    liveLabel: 'Try web demo',
    howTitle: 'How inventory & sales work',
    how: 'Flutter POS scans barcode → Hive caches locally → Firebase syncs → stock auto-deducts, low-stock alerts trigger, treasury updates and invoices generate. Works offline then syncs.',
    run: '1) Download APK above and install on Android\n2) Or: flutter pub get && flutter run  (Hive local DB + Firebase)',
    featured: false,
    group: 'software',
  },
  {
    id: '03',
    type: 'Backend · Java',
    title: 'VELOX — Modular Commerce Engine',
    desc: 'E-commerce engine and delivery system built with Java and Maven using object-oriented design.',
    tech: ['Java 17', 'Maven', 'OOP'],
    year: '2025',
    image: '/assets/project-velox.png',
    github: 'https://github.com/nabosallem-svg/VELOX',
    demo: '/Velox.jar',
    demoLabel: 'Download JAR',
    howTitle: 'How to run locally',
    how: 'Polymorphic stores (Fashion/Tech/Restaurant) with Strategy discounts and pluggable payments. Delivery simulation included.',
    run: '1) java -jar Velox.jar\n2) Or: mvn clean package && mvn exec:java\n3) Or: mvn package && java -jar target/Velox-1.0.jar',
    featured: false,
    group: 'software',
  },
  {
    id: '04',
    type: 'Desktop · C++',
    title: 'Numerical Calculator GUI',
    desc: 'Advanced desktop calculator with a clean Qt interface — precise operations and error handling.',
    tech: ['C++', 'Qt Creator', 'CMake'],
    year: '2024',
    image: '/assets/project-calculator.png',
    github: 'https://github.com/nabosallem-svg/Numerical-Calculator-GUI',
    demo: 'https://github.com/nabosallem-svg/Numerical-Calculator-GUI',
    demoLabel: 'Open Repo',
    howTitle: 'How to run locally',
    how: 'Qt Widgets GUI with expression parser and validation. CMake builds on Windows/Linux.',
    run: '1) Qt Creator → open CMakeLists.txt → Build & Run\n2) Or: cmake -B build && cmake --build build && ./build/Calculator',
    featured: false,
    group: 'software',
  },

  // ——— Added: projects from GitHub ———
  {
    id: '05',
    type: 'Healthcare · Java',
    title: 'NOOR Dental Clinic',
    desc: 'Arabic patient booking system — service, doctor and slot selection, OTP verification, self-service booking links, reception board and clinic finance.',
    tech: ['Spring Boot', 'Java 17', 'H2', 'WhatsApp API'],
    year: '2026',
    image: '/assets/project-clinic.png',
    video: '/assets/clinic-demo.webm',
    github: 'https://github.com/nabosallem-svg/datagris-clinic',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'How it works',
    how: 'Patient picks service → doctor → day → free slot. Overlapping bookings are serialized with a doctor-row lock inside a transaction. OTP-verified sessions, hashed 256-bit management links, CSRF-protected staff APIs with role checks, audit log, payments and doctor dues, WhatsApp confirmations and reminders.',
    run: '1) mvn test\n2) mvn package -DskipTests\n3) java -jar target/clinic-0.1.0.jar  →  http://127.0.0.1:8080',
    featured: false,
    group: 'web',
  },
  {
    id: '06',
    type: 'Web · Coaching Platform',
    title: 'Coach Junior',
    desc: 'Arabic-first (RTL) online bodybuilding coaching — animated landing page plus a trainee app and coach panel.',
    tech: ['Next.js', 'TypeScript', 'Tailwind', 'GSAP', 'Supabase'],
    year: '2026',
    image: '/assets/project-coach.png',
    github: 'https://github.com/nabosallem-svg/coach-junior',
    demo: 'https://coach-junior.vercel.app',
    demoLabel: 'Open Live',
    howTitle: 'How it works',
    how: 'Landing page in one hand-written HTML file with self-hosted GSAP, ScrollTrigger and Lenis, AVIF/WebP images and an English toggle. The platform (Next.js App Router) holds the trainee app and the coach panel, with Supabase schema and row-level security ready.',
    run: '1) cd platform && npm install\n2) npm run dev  →  http://localhost:3000\n3) Landing: npm run build  (src/index.html → index.html)',
    featured: false,
    group: 'web',
  },
  {
    id: '07',
    type: 'Web · Quran Academy',
    title: 'Al-Itqan Quran Academy',
    desc: 'Arabic (RTL) site for an online Quran academy — trial session booking, level test, audio library, payment and student pages.',
    tech: ['HTML', 'Tailwind CSS', 'RTL'],
    year: '2026',
    image: '/assets/project-noor.png',
    github: 'https://github.com/nabosallem-svg/noor-quran-site',
    demo: '/demos/noor-quran/index.html',
    demoLabel: 'Open Live',
    howTitle: 'Pages',
    how: 'Home, booking (trial session), level test, audio library & blog, payment and student dashboard — mobile-first, IBM Plex Sans Arabic and Noto Naskh Arabic typography.',
    run: '1) git clone https://github.com/nabosallem-svg/noor-quran-site\n2) python3 -m http.server 8000  →  http://localhost:8000',
    featured: false,
    group: 'web',
  },
  {
    id: '08',
    type: 'Business Software',
    title: 'Pharmacy Management System',
    desc: 'Medicine inventory, POS workflows, and expiration tracking in one complete system.',
    tech: ['Python', 'CustomTkinter', 'SQLite', 'OpenCV'],
    year: '2025',
    image: '/assets/project-pharmacy.png',
    github: 'https://github.com/nabosallem-svg/Pharmacy-Management-System',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'How it works',
    how: 'Sidebar app with Point of Sale (always open), password-protected inventory and reports. Barcode scanning via camera, Arabic RTL receipts and printing, Excel import/export.',
    run: '1) pip install -r requirements.txt\n2) python app.py',
    featured: false,
    group: 'software',
  },
  {
    id: '09',
    type: 'Artificial Intelligence',
    title: 'Full-Stack AI Web Chatbot',
    desc: 'A dynamic Gemini-powered chat experience with Firebase cloud storage.',
    tech: ['Flutter Web', 'Gemini API', 'Firebase'],
    year: '2025',
    image: '/assets/project-chatbot.png',
    github: 'https://github.com/nabosallem-svg/AI-Web-Chatbot',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'How it works',
    how: 'Flutter Web front end sends prompts to the Gemini API, Firebase Auth signs users in and Cloud Firestore keeps each user’s chat history.',
    run: '1) flutter pub get\n2) flutter run -d chrome',
    featured: false,
    group: 'ai',
  },
  {
    id: '10',
    type: 'Computer Vision',
    title: 'Subsurface Object Detection',
    desc: 'Detecting underground objects from GPR imagery with a custom vision pipeline.',
    tech: ['YOLO', 'Python', 'OpenCV', 'GPR'],
    year: '2025',
    image: '/assets/project-gpr.png',
    github: '',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'Pipeline',
    how: 'GPR image preprocessing → dataset preparation & labeling → YOLO detection with bounding-box overlay.',
    run: 'Python + OpenCV preprocessing, YOLO training and inference.',
    featured: false,
    group: 'ai',
  },

  // ——— DEPI Software Testing track ———
  {
    id: '11',
    type: 'QA · Manual Testing',
    title: 'ISTQB Manual Testing — Add to Cart',
    desc: 'Functional and non-functional manual testing of an online store’s Add to Cart feature (UC-ADD-CART-01).',
    tech: ['ISTQB', 'Test Cases', 'Checklist'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Manual-Testing-AddToCart',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'Deliverables',
    how: 'Test cases, checklist and summary report for the Add to Cart use case.',
    run: 'docs/A_Test_Cases.md · docs/B_Checklist.md · docs/C_Report_Summary.md',
    featured: false,
    group: 'depi',
  },
  {
    id: '12',
    type: 'QA · Static Testing',
    title: 'ISTQB Static Testing — Money Transfer',
    desc: 'Static testing (verification) of a Transfer Money feature from its use case and BankingService.transfer() code.',
    tech: ['ISTQB', 'Inspection', 'Defect Reports'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Static-Testing-Transfer',
    demo: '',
    demoLabel: 'Open',
    howTitle: 'Deliverables',
    how: 'Test plan, checklist, inspection report, defect reports and summary report for UC-TR-01.',
    run: 'docs/01_Static_Test_Plan.md → docs/05_Summary_Report.md',
    featured: false,
    group: 'depi',
  },
  {
    id: '13',
    type: 'DEPI · Java',
    title: 'Student Management System',
    desc: 'Students, instructors, courses and grades modeled with an abstract Person base class.',
    tech: ['Java', 'OOP', 'Maven'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Student-Management-GP11',
    demo: '/downloads/depi-student-management-gp11.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Classes',
    how: 'Person (abstract), Student, Instructor, Course, Grade, StudentManagementSystem.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-student-management-gp11.jar',
    featured: false,
    group: 'depi',
  },
  {
    id: '14',
    type: 'DEPI · Java',
    title: 'E-Commerce Inventory',
    desc: 'Inventory and cart built on an abstract Item hierarchy — clothing and devices.',
    tech: ['Java', 'Inheritance', 'Maven'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-ECommerce-Task09A',
    demo: '/downloads/depi-ecommerce-task09a.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Classes',
    how: 'Item (abstract), Clothing, Device, Shirt, Socks, Hat, Printer, Laptop, Projector, Cart.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-ecommerce-task09a.jar',
    featured: false,
    group: 'depi',
  },
  {
    id: '15',
    type: 'DEPI · Java',
    title: 'University Department',
    desc: 'Department model with theory and lab courses on an abstract Course class.',
    tech: ['Java', 'Abstraction', 'Maven'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-University-Task09B',
    demo: '/downloads/depi-university-task09b.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Classes',
    how: 'Abstract Course, TheoryCourse, LabCourse, Student, Department.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-university-task09b.jar',
    featured: false,
    group: 'depi',
  },
  {
    id: '16',
    type: 'DEPI · Java',
    title: 'Soccer League System',
    desc: 'Teams, players, matches and goals with automatic standings and match details.',
    tech: ['Java', 'Composition', 'ArrayList'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Soccer-League-System-Assignment02',
    demo: '/downloads/depi-soccer-league-system-assignment02.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Classes',
    how: 'Player, Team, Goal, Match, Schedule — updateStatistics() for goals and points, getRankedTeams() for the table.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-soccer-league-system-assignment02.jar',
    featured: false,
    group: 'depi',
  },
  {
    id: '17',
    type: 'DEPI · Java',
    title: 'Shopping System',
    desc: 'Customer carts and generated bills in a simple store, built with composition.',
    tech: ['Java', 'Composition', 'ArrayList'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Shopping-System-Assignment03',
    demo: '/downloads/depi-shopping-system-assignment03.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Classes',
    how: 'Item, Cart, Bill, Customer — the bill is created from a cart and calculates the total.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-shopping-system-assignment03.jar',
    featured: false,
    group: 'depi',
  },
  {
    id: '18',
    type: 'DEPI · Java',
    title: 'Java Collections',
    desc: 'The same item data managed with arrays, lists, sets and maps side by side.',
    tech: ['Java', 'Collections'],
    year: '2026',
    github: 'https://github.com/nabosallem-svg/DEPI-Java-Collections-Task08',
    demo: '/downloads/depi-java-collections-task08.jar',
    demoLabel: 'Download JAR',
    howTitle: 'Collections used',
    how: 'Array, 2D Array, List, ArrayList, LinkedList, Set, HashSet, HashMap.',
    run: '1) Download the JAR above (needs Java 17+)\n2) java -jar depi-java-collections-task08.jar',
    featured: false,
    group: 'depi',
  },
];

export const projects: Project[] = list.map((p) => ({ ...p, output: outputs[p.id] }));
